# Generated by Django 5.1.7 on 2025-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='Apple', max_length=20),
            preserve_default=False,
        ),
    ]
